version: "3.9"
services:
  backend:
    build: ./backend
    container_name: eshop_backend_test
    env_file:
      - .env.test
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
    depends_on:
      - db_test

  db_test:
    image: postgres:16
    container_name: eshop_db_test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: eshop_test
    tmpfs:
      - /var/lib/postgresql/data
